# Generated by Django 4.2.7 on 2023-12-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('bl', 'blue'), ('gr', 'green'), ('pu', 'purple'), ('re', 'red')], default='bl', max_length=2),
        ),
    ]
